preload: ignore clang variable sized type not at end warning
fix CI build errors on clang due to hsm_copy not being last:
../preload/preload.h:59:18: error: field 'copy' with variable sized type 'struct hsm_copy' not at the end of a struct or class is a GNU extension [-Werror,-Wgnu-variable-sized-type-not-at-end]
   59 |         struct hsm_copy copy;
      |                         ^
1 error generated.

This "problem" is the same as in llapi's lustre_hsm.c and they just don't
copy the variable length field (hai data) in this field

Change-Id: Idaf801e53dc163cc5c414aeca3d1ab9373602bae